name: Terraform initialization and deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  OpenId-Connector:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OpenIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::229535137990:role/GithubActionsRole"
          role-session-name: github-actions-session
          aws-region: "us-east-1"
      
      - name: Debug AWS credentials
        run: |
            aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6
      - name: Terraform Init
        run: terraform init

      - name: terraform-check
        run: terraform fmt -check
         
      - name: terraform-plan
        run: terraform plan

      - name: terraform-apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
